FoxholeTrainLogistics/Models/ErrorViewModel.cs
namespace Test.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FoxholeTrainLogistics/Models/Train.cs
using FoxholeTrainLogistics.Interfaces;
using System.ComponentModel.DataAnnotations.Schema;

namespace FoxholeTrainLogistics.Models
{
    public class Train : ITrain
    {
        public Guid TrainId { get; set; }
        public TrainStatus Status { get; set; }

        [NotMapped] // .. TODO: this should probably be a many-to-many relationship between other "Cars" in the database
        public List<ITrainCar> Cars { get; set; } = new List<ITrainCar>();
    }
}

FoxholeTrainLogistics/ViewModels/DatePickerViewModel.cs
namespace FoxholeTrainLogistics.ViewModels
{
    public class DatePickerViewModel
    {
        public Guid Id { get; set; }

        public DatePickerViewModel(Guid id)
        {
            Id = id;
        }
    }
}

FoxholeTrainLogistics/ViewModels/ErrorViewModel.cs
namespace FoxholeTrainLogistics.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FoxholeTrainLogistics/ViewModels/ShippableIconViewModel.cs
using FoxholeTrainLogistics.Interfaces;

namespace FoxholeTrainLogistics.ViewModels
{
    public class ShippableIconViewModel : IShippableIcon
    {
        public string ImagePath { get; private set; }
        public string Name { get; private set; }
        public string DisplayName { get; private set; }

        public ShippableIconViewModel(string imagePath, string name, string displayName)
        {
            ImagePath = imagePath;
            Name = name;
            DisplayName = displayName;
        }
    }
}

FoxholeTrainLogistics/ViewModels/ShippableToolbarViewModel.cs
using FoxholeItemAPI.Interfaces;
using FoxholeItemAPI.Utils;
using FoxholeTrainLogistics.Interfaces;

namespace FoxholeTrainLogistics.ViewModels
{
    public class ShippableToolbarViewModel
    {
        private IShippableToolbarService _shippableToolbarService;

        public List<IShippableIcon> ShippableCategories { get; private set; }

        public Dictionary<string, List<IItem>>? _shippableItems = null;

        public ShippableToolbarViewModel(IShippableToolbarService shippableToolbarService)
        {
            ShippableCategories = shippableToolbarService.GetShippableCategories();

            _shippableToolbarService = shippableToolbarService;
        }

        public async Task<Dictionary<string, List<IItem>>> GetShippableItems()
        {
            if(_shippableItems == null)
                _shippableItems = await _shippableToolbarService.GetShippableItems();

            return _shippableItems;
        }
    }
}

FoxholeTrainLogistics/ViewModels/TrainViewModel.cs
using FoxholeTrainLogistics.Interfaces;

namespace FoxholeTrainLogistics.Models
{
    public class TrainViewModel
    {
        public ITrain Train;
        public string StatusDisplayName => Train.Status.GetDisplayName();
        public int NumberOfCars => Train.Cars.Count;
        public bool Interactable = false;

        public TrainViewModel(ITrain _train, bool interactable = false)
        {
            Train = _train;
            Interactable = interactable;
        }
    }
}

FoxholeTrainLogistics/ViewModels/TrainsViewModel.cs
namespace FoxholeTrainLogistics.Models
{
    public class TrainsViewModel
    {
        public List<TrainViewModel> Trains { get; set; } = new List<TrainViewModel>();
    }
}

FoxholeTrainLogistics/Controllers/HomeController.cs
using FoxholeTrainLogistics.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FoxholeTrainLogistics.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FoxholeTrainLogistics/Controllers/ShipmentCalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;

namespace FoxholeTrainLogistics.Controllers
{
    public class ShipmentCalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FoxholeTrainLogistics/Controllers/TrainsController.cs
using FoxholeTrainLogistics.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FoxholeTrainLogistics.Models;

namespace FoxholeTrainLogistics.Controllers
{
    public class TrainsController : Controller
    {
        private readonly ITrainsDbContext _dbContext;

        public TrainsController(ITrainsDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        // GET: TrainsController
        public ActionResult Index()
        {
            var trainsViewModel = new TrainsViewModel()
            {
                Trains = _dbContext.Trains.Select(t => new TrainViewModel(t,false)).ToList()
            };

            return View(trainsViewModel);
        }

        // GET: TrainsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TrainsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TrainsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TrainsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TrainsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TrainsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TrainsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FoxholeTrainLogistics/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Foxhole Train Logistics!</h1>
    <img src="./img/trains/engineCarBlack.png"/>
    <p>The trains WILL run on time.</p>
</div>

FoxholeTrainLogistics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Foxhole Train Logistics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ftl-input.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoxholeTrainLogistics.styles.css" asp-append-version="true" />

    
    <script src="~/js/trainsFactory.js"></script>
    <script src="~/js/EventManager.js"></script>
    <script src="~/js/InputManager.js"></script>
    <script src="~/js/Utils.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>

    <header>
        <partial name="_Nav" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NadoCo Interactive - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="https://kit.fontawesome.com/9d5c7d3cb0.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FoxholeTrainLogistics/Views/Shared/_Nav.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Foxhole Train Logistics</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Trains" asp-action="Index">Trains</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="ShipmentCalculator" asp-action="Index">Calculator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

FoxholeTrainLogistics/Views/Shared/_TrainsUtils.cshtml
@using FoxholeItemAPI.Utils;
@using FoxholeItemAPI.Models;
@using System.Text.Json;
@using FoxholeTrainLogistics.Services;
@using FoxholeTrainLogistics.Interfaces;
@inject IShippableToolbarService shippableToolbarService;

<script>
    var Category = @Html.Raw(JsonSerializer.Serialize(ApiUtils.EnumTypesToString<Category>()));
    var ShippingType = @Html.Raw(JsonSerializer.Serialize(ApiUtils.EnumTypesToString<ShippingType>()));
    var TrainCarType = @Html.Raw(JsonSerializer.Serialize(ApiUtils.EnumTypesToString<TrainCarType>()));
    var PackageType = { 0: "singlePackaged", 1: "mpfCrate" };
    var Faction = {0: "colonial", 1: "warden", 2: "neutral"};

    var TrainCarTemplates = @Html.Raw(TrainCarFactory.GetTrainCarTemplates().ToDictionary().ToJson());
    var ItemTemplates = @Html.Raw((await shippableToolbarService.GetShippableItems()).ToJson());

    var PackagedItemContainerTemplate = @Html.Raw(ContainerFactory.CreatePackagedItemContainer(new Item()).ToJson());
    var MultiItemContainerTemplates = @Html.Raw(ContainerFactory.GetMultiItemContainerTemplates().ToDictionary().ToJson());

    function InvertEnum (_enum) {
        if (typeof _enum !== "object")
            throw new DOMException("The given enum must be an object");

        var enumInvertedEntries = Object.values(_enum).map((v, i) => [v, Object.keys(_enum)[i]]);
        return Object.fromEntries(enumInvertedEntries);
    }
</script>

FoxholeTrainLogistics/Views/ShipmentCalculator/Index.cshtml
@using FoxholeTrainLogistics.Interfaces;
@using FoxholeTrainLogistics.Services;
@using FoxholeTrainLogistics.ViewModels;
@inject IShippableToolbarService ShippableToolbarService;
@{
ViewData["Title"] = "Shipment Calculator";
}

@{
    await Html.RenderPartialAsync("_TrainsUtils");
}

<script>
    @{
        var train = new Train()
        {
        TrainId = Guid.NewGuid(),
            Cars = new List < ITrainCar > () {
            TrainCarFactory.CreateTrainCar(TrainCarType.EngineCar),
                TrainCarFactory.CreateTrainCar(TrainCarType.CoalCar)
        },
        Status = TrainStatus.Parked
    };
    }
</script>

<h1>Shipment Calculator</h1>

<div>
    <b>Your Train</b>
    @{await Html.RenderPartialAsync("../Trains/_Train", new TrainViewModel(train,true));}
</div>
<div style="border-top: 1px solid #ababab; border-bottom: 1px solid #ababab; margin-top: 10px; margin-bottom: 5px; padding: 10px; height: 150px">
    <h3>Shipment Info</h3>
    <div style="display: flex; flex-direction: row">
        @{
            var shipmentDatePickerId = Guid.NewGuid();
        }

        <script type="text/javascript">
            
            function setError(text) {
                const errorElement = document.getElementById("shipment-error");

                if(text === '' || text === undefined)
                    errorElement.style.display = 'none';
                else
                    errorElement.innerHTML = text;
            }

            function parseDate (dateString) {
                const dateParts = dateString.split(/[-T:]/);
                const year = parseInt(dateParts[0], 10) + 2000;
                const month = parseInt(dateParts[1], 10) - 1;
                const day = parseInt(dateParts[2], 10);
                const hour = parseInt(dateParts[3], 10);
                const minute = parseInt(dateParts[4], 10);

                const hourNow = new Date().getHours();
                const minuteNow = new Date().getMinutes();
                return new Date(year, month, day, !isNaN(hour) ? hour : hourNow, !isNaN(minute) ? minute : minuteNow);
            }

            function validateForm() {
                var errors = [];

                const shipmentDate = document.getElementById("shipment-date");
                const shipmentDateIsDate = !isNaN(parseDate(shipmentDate.value)) || shipmentDate.value === '';

                if(!shipmentDateIsDate)
                {
                    errors.push('Please enter a valid Shipment Date like "DD-MM-YYTHH:MM"');
                    shipmentDate.style.borderColor = 'red';
                }
                else
                    shipmentDate.style.borderColor = '';

                setError(errors.join(' | '));
            }

            function handleCopyDiscordMessage()
            {
                const shipmentNameInput = document.getElementById("shipment-name");
                const shipmentName = shipmentNameInput.value != '' ? shipmentNameInput.value : shipmentNameInput.placeholder;
                const shipmentDateInput = document.getElementById("ftl-dp-input-@shipmentDatePickerId");
                const shipmentDate = shipmentDateInput.value != '' ? shipmentDateInput.value : shipmentDateInput.placeholder;
                const shipFromInput = document.getElementById("shipment-from");
                const shipFrom = shipFromInput.value != '' ? shipFromInput.value : shipFromInput.placeholder;
                const shipToInput = document.getElementById("shipment-to");
                const shipTo = shipToInput.value != '' ? shipToInput.value : shipToInput.placeholder;
                const requestedByInput = document.getElementById("shipment-requested-by");
                const requestedBy = requestedByInput.value != '' ? requestedByInput.value : requestedByInput.placeholder;
                const shipmentWhenInput = document.getElementById("shipment-when");
                const shipmentWhen = shipmentWhenInput.value != '' ? shipmentWhenInput.value : shipmentWhenInput.placeholder;

                var discordMessage = ``;
                discordMessage += "------------------------------------------------------\n";
                discordMessage += `** ${shipmentName} - ${shipmentDate}**\n`;
                discordMessage += `\n`;
                discordMessage += `**From: **${shipFrom}\n`;
                discordMessage += `**To: **${shipTo}\n`;
                discordMessage += `**Requested By: **${requestedBy}\n`;
                discordMessage += `**When: **${shipmentWhen}\n`;
                discordMessage += `\n`;

                const trainFlatbeds = train.Cars.filter(c => c.Type === 'FlatbedCar');

                trainFlatbeds.map((fb,i) => {
                    discordMessage += `**Flatbed ${i+1}:** ${fb.Container.DisplayName}\n`;

                    const containerContents = fb.Container.Contents;
                    const containerContentsNames = containerContents.map(item => item.DisplayName);
                    const uniqueContainerContents = containerContents.filter((v, i, s) => containerContentsNames.indexOf(v.DisplayName) === i);
                    
                    uniqueContainerContents.map(item => {
                        const itemName = `${item.DisplayName} ${fb.Container.isMPF ? "(Crate of 3)" : ""}`;
                        const itemCountRaw = containerContents.filter(c => c.IconName === item.IconName).length;
                        const itemCount = fb.Container.isMPF ? 1 : itemCountRaw;
                        const itemCountString = fb.Container.Type !== "ShippingContainer" ? `**x${itemCount}**` : `(Crates: **${itemCount}**)`

                        discordMessage += ` - ${itemName} ${itemCountString}\n`;
                    });
                    discordMessage += `\n`;
                });

                console.log(discordMessage);

                const discordMessageTextArea = document.createElement('textarea');
                discordMessageTextArea.value = discordMessage;

                document.body.appendChild(discordMessageTextArea);

                discordMessageTextArea.select();
                document.execCommand("copy");
                document.body.removeChild(discordMessageTextArea);

                alert("Discord message copied! Paste it in any discord chat!");
            }
        </script>
        <div style="width: 300px">
            <label for="shipment-name">Shipment Name</label>
            <input type="text" class="form-control" id="shipment-name" aria-describedby="basic-addon3" placeholder="New Shipment">
        </div>
        @{
            await Html.RenderPartialAsync("_DatePicker",new DatePickerViewModel(shipmentDatePickerId));
        }
        <div style="width: 200px; margin-left: 10px">
            <label for="shipment-from">Ship From</label>
            <input type="text" class="form-control" id="shipment-from" aria-describedby="basic-addon3" placeholder="Point A">
        </div>
        <div style="width: 200px; margin-left: 10px">
            <label for="shipment-to">Ship To</label>
            <input type="text" class="form-control" id="shipment-to" aria-describedby="basic-addon3"  placeholder="Point B">
        </div>
        <div style="width: 200px; margin-left: 10px">
            <label for="shipment-requested-by">Requested By</label>
            <input type="text" class="form-control" id="shipment-requested-by" aria-describedby="basic-addon3"  placeholder="Logistics Coordinator">
        </div>
        <div style="width: 200px; margin-left: 10px">
            <label for="shipment-when">When</label>
            <input type="text" class="form-control" id="shipment-when" aria-describedby="basic-addon3"  placeholder="ASAP">
        </div>
    </div>
    <label id="shipment-error" style="color: red"></label>
</div>
<div style="display: flex;">
    @{await Html.RenderPartialAsync("./_ShippableToolbar", new ShippableToolbarViewModel(ShippableToolbarService));}
    <div style="width: 10px"></div>
    @{await Html.RenderPartialAsync("./_TrainCarViewer");}
</div>
<div style="margin-top: 10px;">
    <button type="button" class="btn btn-primary ftl-interact-minimal" onclick="handleCopyDiscordMessage()">Copy Discord Message</button>
</div>

FoxholeTrainLogistics/Views/ShipmentCalculator/_ShippableToolbar.cshtml
@using FoxholeTrainLogistics.ViewModels;
@using FoxholeItemAPI.Interfaces;
@using FoxholeItemAPI.Utils;
@model ShippableToolbarViewModel

<script>
    var selectedFaction = Faction[2];
    var selectedCategory = '';

    localStorage.packageOption = PackageType[1];

    function onFactionChanged(faction) {
        const factionsToShow = faction !== 'neutral' ? [faction, 'neutral'] : Object.values(Faction);
        const elementsToShow = document.querySelectorAll(`.${factionsToShow.join(",.")}`);
        elementsToShow.forEach(e => e.style.display = "inline");

        const factionsToHide = faction !== 'neutral' ? Object.values(Faction).filter(f => f !== faction && f !== 'neutral') : [];
        const elementsToHide = factionsToHide.length > 0 ? document.querySelectorAll(`.${factionsToHide.join(",.")}`) : [];
        elementsToHide.forEach(e => e.style.display = "none");
    }

    onFactionChanged("neutral");
</script>


<script>
    var selectedTrainCar = undefined;

    function updatePackageRadios(shippingType) {
        var packageRadios = document.getElementById("packageRadios");
        packageRadios.style.display = shippingType === "CrateOrPackage" ? 'inline' : 'none';
    }

    function handleTabClicked(shippingType) {
        updatePackageRadios(shippingType);
    }

    function handleAddItemToTrain(item) {
        var updatedFlatcar = undefined;

        if (!InputManager.MultiplyTen && !InputManager.MultiplyHundred)
            updatedFlatcar = train.AddItem(item, selectedTrainCar);
        else if (InputManager.MultiplyTen) {
            for (var i = 0; i < 10; i++)
                updatedFlatcar = train.AddItem(item, selectedTrainCar)
        }
        else {
            for (var i = 0; i < 100; i++)
                updatedFlatcar = train.AddItem(item, selectedTrainCar)
        }

        EventManager.DispatchEvent("selectedTrainCarChanged", updatedFlatcar);
    }

    document.addEventListener("DOMContentLoaded",() => {
        EventManager.AddEventListener("selectedTrainCarChanged", (car) => {
            selectedTrainCar = car;
        });

        updatePackageRadios();
    })//
</script>
<div class="ftl-paper" style="flex: 1; min-height: 500px; margin-top: 5px;">
    <ul class="nav nav-tabs" id="ftl-shippableTabs" role="tablist"
        style="overflow-x: scroll; overflow-y: hidden; display: flex; flex-wrap: nowrap">
        @{
            foreach (ShippableIconViewModel category in Model.ShippableCategories)
            {
                Category categoryAsEnum = Enum.Parse<Category>(category.DisplayName.Replace(" ", ""));
                <li class="nav-item" role="presentation">
                    <button class="nav-link @(Model.ShippableCategories.IndexOf(category)==0 ? " active" : "" )"
                        onclick="handleTabClicked('@categoryAsEnum.ToShippingType()')" id="@category.Name-tab"
                        data-bs-toggle="tab" data-bs-target="#@category.Name" type="button" role="tab"
                        aria-controls="@category.Name" aria-selected="true">
                        <img class="ftl-icon ftl-noselect ftl-shippable-icon" src="@category.ImagePath?v=-1"
                         data-bs-toggle="tooltip" data-bs-placement="top" title="@category.DisplayName" />
                    </button>
                </li>
            }
        }
    </ul>
    <div class="tab-content" id="ftl-shippableTabsContent">
        @{

        <div style="display: flex;padding: 10px; ">
            <div id="factionRadios" style="flex: 1; display: flex; justify-content: center; align-items: center">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="factionRadios" id="radio-colonial" value="0" />
                    <label class="form-check-label" for="radio-colonial">Colonial</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="factionRadios" id="radio-warden" value="1" />
                    <label class="form-check-label" for="radio-warden">Warden</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="factionRadios" id="radio-neutral" value="2"
                        checked />
                    <label class="form-check-label" for="radio-neutral">Neutral</label>
                </div>
                <script>
                    var radioGroup = document.getElementById("factionRadios");

                    radioGroup.addEventListener("change", function ({ target: { value } }) {
                        onFactionChanged(Faction[value]);
                    });
                </script>
            </div>

            <div id="packageRadios" style="flex: 1;  display: flex; justify-content: center; align-items: center; display: none">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="packageRadios" id="radio-mpf-crate" value="1"
                        checked />
                    <label class="form-check-label" for="radio-mpf-crate">MPF Crate</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="packageRadios" id="radio-single-packaged"
                        value="0" />
                    <label class="form-check-label" for="radio-single-packaged">Single Packaged</label>
                </div>
                <script>
                    var radioGroup = document.getElementById("packageRadios");

                    radioGroup.addEventListener("change", function ({ target: { value } }) {
                        localStorage.packageOption = PackageType[value];
                    });
                </script>
            </div>


        </div>

        foreach (ShippableIconViewModel category in Model.ShippableCategories)
        {
            <div class="tab-pane fade @(Model.ShippableCategories.IndexOf(category)==0 ? " show active" : "" )"
                id="@category.Name" role="tabpanel" aria-labelledby="@category.Name-tab">
                    @{
                        var categoryItems = (await Model.GetShippableItems())[category.Name];


                foreach (IItem item in categoryItems)
                {
                    <button class="ftl-interact ftl-button @item.Faction.ToString().ToLower()"
                        style="width: 72px; height: 72px; margin-right: -2px; text-align: center; vertical-align: middle; position: relative;"
                        onclick="handleAddItemToTrain(@(item.ToString()));">
                        <img class="ftl-icon ftl-noselect ftl-shippable-icon" src="@item.IconName?v=-1"
                            style="padding: 0px; transform: scale(150%);" data-bs-toggle="tooltip" data-bs-placement="top"
                            title="@item.DisplayName" />
                    </button>
                }
                }
            </div>
        }

        }
    </div>
</div>

FoxholeTrainLogistics/Views/Trains/Index.cshtml
@model TrainsViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Trains</h1>
<div>
    @foreach (var t in Model.Trains)
    {
        await Html.RenderPartialAsync("_Train", t);
    }
</div>

FoxholeTrainLogistics/Views/Trains/_Train.cshtml
@using FoxholeTrainLogistics.Interfaces;
@using FoxholeTrainLogistics.Services;
@using System.Text.Json;
@using System.Text.Json.Serialization;
@{
    var serializerOptions = new JsonSerializerOptions() { Converters = { new JsonStringEnumConverter() } };
}
@model TrainViewModel

<!-- Import Train Creation Factory-->

<script src="~/js/train.js?v=-1"></script>
<script>
    var selectedTrainCar = undefined;

    var train;
    document.addEventListener('DOMContentLoaded', () => {
        const trainObj = @Html.Raw(JsonSerializer.Serialize(Model.Train,serializerOptions));
        train = new Train(trainObj, @Model.Interactable.ToString().ToLower());
    });

    EventManager.AddEventListener("selectedTrainCarChanged", (car) => {
        selectedTrainCar = car
    });

    if((@Model.Interactable.ToString().ToLower()))
    {
        document.addEventListener('keydown',function ({key}) {
            if(key === "Delete" && selectedTrainCar) {
                train.RemoveTrainCar(selectedTrainCar.id);
                EventManager.DispatchEvent("selectedTrainCarChanged");
            }
        });
    }
</script>

<div class="ftl-paper" style="margin-bottom: 5px; min-height: 100px; display: flex; flex-direction: column">
    <span>@Model.Train.TrainId</span>

    <div id=@("train-container-"+Model.Train.TrainId)
        style="display: flex; vertical-align: middle; margin-top: 5px; margin-bottom: 5px; min-height: 50px">
    </div>

    <div class="btn-group" role="group">
        <button type="button" class="ftl-interact ftl-chip">@Model.NumberOfCars Cars</button>
        <button id=@("train-crew-"+Model.Train.TrainId) type="button" class="ftl-interact ftl-chip">
            Crew Capacity: 2
        </button>

        <button type="button" class="ftl-interact ftl-chip @Model.Train.Status.ToAlert()">Status: @Model.StatusDisplayName</button>
    </div>
</div>

@if (!Model.Interactable)
    return;


<div class="ftl-paper" style=" display: flex; min-height: 75px; width: fit-content; min-width: 500px">
    <div id=@("train-toolbar-"+Model.Train.TrainId) style=" display: flex; ">
        @foreach (ITrainCar car in TrainCarFactory.GetTrainCarTemplates())
        {
            <button class="ftl-noselect ftl-interact ftl-button" onclick="train.AddTrainCar({...@car});">
                <img class="ftl-icon" src="/img/trains/@(car.Image)?v=-1" data-bs-toggle="tooltip" data-bs-placement="top"
                title="@car.Type.GetDisplayName()" />
            </button>
        }
    </div>
</div>